pub mod app;
#[cfg(feature = "local-asr")]
pub mod asr;
pub mod audit;
pub mod chat;
pub mod formation;
pub mod hardware;
pub mod meeting;
pub mod memory;
pub mod models;
pub mod ollama;
pub mod session;
pub mod settings;
pub mod tasks;
