import { type ByokConfig, tauri } from "@/lib/tauri";
import { useEffect, useState } from "react";

/// Settings overlay. Currently the BYOK (bring-your-own-key) cloud config:
/// with a provider and key set, Ask-mode answers are generated by that cloud
/// model instead of the local one. Extraction always stays local.
export function SettingsModal({ onClose }: { onClose: () => void }) {
  const [provider, setProvider] = useState("");
  const [model, setModel] = useState("");
  const [apiKey, setApiKey] = useState("");
  const [hasKey, setHasKey] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    tauri
      .getByokConfig()
      .then((c: ByokConfig) => {
        setProvider(c.provider ?? "");
        setModel(c.model ?? "");
        setHasKey(c.has_key);
      })
      .catch((e) => setError(e instanceof Error ? e.message : String(e)))
      .finally(() => setLoading(false));
  }, []);

  // Switching off BYOK clears the saved key; require a key when turning it on.
  const needsKey = provider !== "" && !hasKey && apiKey.trim() === "";

  async function save() {
    setSaving(true);
    setError(null);
    try {
      await tauri.setByokConfig(provider || null, model.trim() || null, apiKey.trim() || null);
      onClose();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setSaving(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-6">
      <div className="w-full max-w-md space-y-5 rounded-lg border border-zinc-200 bg-white p-6 shadow-lg dark:border-zinc-800 dark:bg-zinc-900">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Settings</h2>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close settings"
            className="rounded px-1.5 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-700 dark:hover:bg-zinc-800 dark:hover:text-zinc-200"
          >
            ✕
          </button>
        </div>

        <section className="space-y-3">
          <div>
            <h3 className="text-xs font-semibold text-zinc-700 dark:text-zinc-300">
              Cloud answers (BYOK)
            </h3>
            <p className="mt-0.5 text-[11px] text-zinc-500 dark:text-zinc-400">
              Generate Ask-mode answers with your own cloud model. Fact extraction always stays
              local. Off uses the local model.
            </p>
          </div>

          {loading ? (
            <p className="text-xs text-zinc-400 dark:text-zinc-500">Loading…</p>
          ) : (
            <>
              <label className="block text-xs text-zinc-600 dark:text-zinc-400">
                Provider
                <select
                  value={provider}
                  onChange={(e) => setProvider(e.target.value)}
                  className="mt-1 block w-full rounded-md border border-zinc-300 bg-white px-2 py-1.5 text-sm text-zinc-900 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
                >
                  <option value="">Off — use the local model</option>
                  <option value="anthropic">Anthropic</option>
                  <option value="openai">OpenAI</option>
                </select>
              </label>

              {provider !== "" && (
                <>
                  <label className="block text-xs text-zinc-600 dark:text-zinc-400">
                    Model
                    <input
                      type="text"
                      value={model}
                      onChange={(e) => setModel(e.target.value)}
                      placeholder={
                        provider === "anthropic" ? "claude-3-5-haiku-latest" : "gpt-4o-mini"
                      }
                      className="mt-1 block w-full rounded-md border border-zinc-300 bg-white px-2 py-1.5 text-sm text-zinc-900 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
                    />
                  </label>

                  <label className="block text-xs text-zinc-600 dark:text-zinc-400">
                    API key
                    <input
                      type="password"
                      value={apiKey}
                      onChange={(e) => setApiKey(e.target.value)}
                      placeholder={hasKey ? "•••••• saved — leave blank to keep" : "Paste your key"}
                      className="mt-1 block w-full rounded-md border border-zinc-300 bg-white px-2 py-1.5 text-sm text-zinc-900 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
                    />
                  </label>
                </>
              )}
            </>
          )}

          {error && <p className="text-xs text-red-600 dark:text-red-400">{error}</p>}
        </section>

        <div className="flex justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            disabled={saving}
            className="rounded-md px-3 py-1.5 text-xs text-zinc-500 hover:bg-zinc-100 disabled:opacity-40 dark:text-zinc-400 dark:hover:bg-zinc-800"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={() => void save()}
            disabled={saving || loading || needsKey}
            className="rounded-md bg-zinc-900 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-40 dark:bg-zinc-100 dark:text-zinc-900"
          >
            {saving ? "Saving…" : needsKey ? "Enter a key" : "Save"}
          </button>
        </div>
      </div>
    </div>
  );
}
