// Core module: long-lived state and subsystems.
pub mod agent_tone;
#[cfg(feature = "local-asr")]
pub mod asr_model;
pub mod audio;
pub mod audit;
pub mod bundled_embed;
pub mod cancel;
pub mod capture;
pub mod capture_pipeline;
pub mod claude_code;
pub mod cli_launch;
pub mod conversation;
pub mod copilot;
pub mod daily_note;
#[cfg(feature = "local-asr")]
pub mod diarization;
pub mod distillation;
pub mod embedding;
pub mod formation_mcp;
pub mod formation_state;
pub mod formation_tools;
pub mod indexer;
pub mod meeting_note;
pub mod memory;
pub mod ollama_sidecar;
#[cfg(feature = "local-asr")]
pub mod ort_runtime;
pub mod pre_pass;
pub mod reminders;
pub mod self_model;
pub mod session;
pub mod task_note;
pub mod tasks;
pub mod transcription;
pub mod watcher;
pub mod working_set;
